// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Vishnu-014/goth-app/components"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><script src=\"/static/htmx.min.js\"></script><title>GOTH Project</title></head><body><h1>Welcome to GOTH Stack 🚀</h1><button hx-get=\"/hello\" hx-target=\"#result\" hx-swap=\"innerHTML\">Click me</button> <button data-tooltip=\"Save changes to server\">💾 Save</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Tooltip().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span data-tooltip-title=\"Popover Title\" data-tooltip-desc=\"Description of what is being displayed, or information that pertains to the tutorial lorem ipsum.\" style=\"cursor: pointer; color: #0055aa;\">⚡️</span> <span data-tooltip-title=\"Popover Title\" data-tooltip-desc=\"Description here...\" data-tooltip-position=\"right\">😂</span> <span data-tooltip-title=\"Popover Title\" data-tooltip-desc=\"This appears at the bottom of the icon.\" data-tooltip-position=\"bottom\" style=\"cursor: pointer;\">bottom</span> <span data-tooltip-title=\"Popover Left\" data-tooltip-desc=\"This appears on the left side.\" data-tooltip-position=\"left\" style=\"cursor: pointer; margin-left: 50px;\">left</span> <button data-tooltip-title=\"Popover Left\" data-tooltip-desc=\"This appears on the left side.\" data-tooltip-position=\"left\" style=\"cursor: pointer; margin-left: 50px;\">left btn</button><div id=\"result\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
